name: jelly_2vm
description: A Lightweight MVVM Microframework for Flutter
version: 0.7.0
homepage: https://github.com/appfactorysrl/jelly-2vm
repository: https://github.com/appfactorysrl/jelly-2vm
issue_tracker: https://github.com/appfactorysrl/jelly-2vm/issues
documentation: https://github.com/appfactorysrl/jelly-2vm/blob/main/README.md

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

